from pathlib import Path
path = Path(r"lib/screens/reservations/reservation_list_screen.dart")
text = path.read_text()
old = """    if (reservations.isEmpty) {\r\n      return Center(\r\n        child: Column(\r\n          mainAxisAlignment: MainAxisAlignment.center,\r\n          children: [\r\n            Container(\r\n              padding: const EdgeInsets.all(40),\r\n              decoration: BoxDecoration(\r\n                color: AppColors.grey100,\r\n                shape: BoxShape.circle,\r\n              ),\r\n              child: Icon(\r\n                isUpcoming ? Icons.event_note : Icons.history,\r\n                size: 80,\r\n                color: AppColors.grey400,\r\n              ),\r\n            ),\r\n            const SizedBox(height: 24),\r\n            Text(\r\n              isUpcoming ? 'Aktif Rezervasyon Yok' : 'Geçmiş Rezervasyon Yok',\r\n              style: const TextStyle(\r\n                fontSize: 20,\r\n                fontWeight: FontWeight.bold,\r\n                color: AppColors.grey900,\r\n              ),\r\n            ),\r\n            const SizedBox(height: 12),\r\n            const Text(\r\n              'Henüz rezervasyon bulunmuyor',\r\n              style: TextStyle(\r\n                fontSize: 14,\r\n                color: AppColors.grey600,\r\n              ),\r\n            ),\r\n          ],\r\n        ),\r\n      );\r\n    }\r\n\r\n    return RefreshIndicator(\r\n      onRefresh: _loadData,\r\n      color: AppColors.primaryOrange,\r\n      child: ListView.builder(\r\n        padding: const EdgeInsets.all(20),\r\n        itemCount: reservations.length,\r\n        itemBuilder: (context, index) {\r\n          final reservation = reservations[index];\r\n          return _buildReservationCard(reservation, isUpcoming);\r\n        },\r\n      ),\r\n    );\r\n  }\r\n"""
new = """    if (reservations.isEmpty) {\r\n      return Padding(\r\n        padding: const EdgeInsets.symmetric(horizontal: 32),\r\n        child: Column(\r\n          mainAxisAlignment: MainAxisAlignment.center,\r\n          children: [\r\n            Container(\r\n              padding: const EdgeInsets.all(36),\r\n              decoration: BoxDecoration(\r\n                gradient: const LinearGradient(\r\n                  colors: [Color(0xFFFFEDD5), Color(0xFFFFFBF5)],\r\n                  begin: Alignment.topLeft,\r\n                  end: Alignment.bottomRight,\r\n                ),\r\n                shape: BoxShape.circle,\r\n                boxShadow: [\r\n                  BoxShadow(\r\n                    color: AppColors.primaryOrange.withOpacity(0.18),\r\n                    blurRadius: 25,\r\n                  ),\r\n                ],\r\n              ),\r\n              child: Icon(\r\n                isUpcoming ? Icons.event_available : Icons.history_toggle_off,\r\n                size: 64,\r\n                color: AppColors.primaryOrange,\r\n              ),\r\n            ),\r\n            const SizedBox(height: 24),\r\n            Text(\r\n              isUpcoming ? 'Henüz aktif rezervasyon yok' : 'Geçmiş kaydın yok',\r\n              style: const TextStyle(\r\n                fontSize: 20,\r\n                fontWeight: FontWeight.bold,\r\n                color: AppColors.grey900,\r\n              ),\r\n              textAlign: TextAlign.center,\r\n            ),\r\n            const SizedBox(height: 12),\r\n            Text(\r\n              isUpcoming\r\n                  ? 'Bugün bir menü seçip yerini garantileyebilirsin.'\r\n                  : 'Yeni rezervasyonların burada listelenecek.',\r\n              style: const TextStyle(\r\n                fontSize: 14,\r\n                color: AppColors.grey600,\r\n              ),\r\n              textAlign: TextAlign.center,\r\n            ),\r\n          ],\r\n        ),\r\n      );\r\n    }\r\n\r\n    return RefreshIndicator(\r\n      onRefresh: _loadData,\r\n      color: AppColors.primaryOrange,\r\n      child: ListView.separated(\r\n        padding: const EdgeInsets.fromLTRB(20, 8, 20, 28),\r\n        physics: const BouncingScrollPhysics(),\r\n        itemCount: reservations.length,\r\n        separatorBuilder: (_, __) => const SizedBox(height: 12),\r\n        itemBuilder: (context, index) =>\r\n            _buildReservationCard(reservations[index], isUpcoming),\r\n      ),\r\n    );\r\n  }\r\n"""
if old not in text:
    raise SystemExit('old block not found for list')
text = text.replace(old, new, 1)
path.write_text(text)
