class AppStrings {
  // Turkish Strings
  static const Map<String, String> tr = {
    // Auth
    'welcome': 'Hoş geldiniz',
    'login': 'Giriş Yap',
    'register': 'Kayıt Ol',
    'email': 'E-posta',
    'password': 'Şifre',
    'confirmPassword': 'Şifre Tekrar',
    'forgotPassword': 'Şifremi Unuttum',
    'dontHaveAccount': 'Hesabınız yok mu?',
    'alreadyHaveAccount': 'Zaten hesabınız var mı?',
    'fullName': 'Ad Soyad',
    'schoolEmail': 'Okul E-postası',
    'phone': 'Telefon Numarası',
    'studentNumber': 'Öğrenci Numarası',
    
    // Home
    'welcomeBack': 'Hoş geldiniz,',
    'cardBalance': 'Kart bakiyeniz',
    'quickActions': 'Hızlı İşlemler',
    'createReservation': 'Rezervasyon\nOluştur',
    'swap': 'Takas',
    'qrPayment': 'QR Ödeme',
    'reservationList': 'Rezervasyon\nListesi',
    'upcomingReservations': 'Yaklaşan Rezervasyonlar',
    'adminPanel': 'Yönetici Paneli',
    
    // Balance
    'loadBalance': 'Bakiye Yükle',
    'amountToLoad': 'Yüklenecek Tutar',
    'minMax': 'Minimum: ₺%.0f - Maksimum: ₺%.0f',
    'quickSelect': 'Hızlı Seçim',
    'transactionHistory': 'İşlem Geçmişi',
    'balanceLoaded': 'Bakiye Yükleme',
    'reservationPayment': 'Rezervasyon Ödemesi',
    'refund': 'İade',
    'mockPaymentNote': '* Bu bir mock ödeme sistemidir. Gerçek üretimde banka uygulamasına yönlendirilirsiniz.',
    
    // Reservations
    'filters': 'FİLTRELE',
    'selectDate': 'Tarih Seç',
    'mealType': 'Yemek Türü',
    'mealPeriod': 'Öğün',
    'normal': 'Normal',
    'vegetarian': 'Vejetaryen',
    'vegan': 'Vegan',
    'glutenFree': 'Glutensiz',
    'breakfast': 'Kahvaltı',
    'lunch': 'Öğle',
    'dinner': 'Akşam',
    'spotsLeft': '%.0f yer kaldı',
    'reservationPrice': 'Rezervasyon Fiyatı',
    'walkInPrice': 'Anında',
    'reserve': 'Rezerve Et',
    'confirmReservation': 'Rezervasyonu Onayla',
    'meal': 'Yemek',
    'date': 'Tarih',
    'time': 'Saat',
    'price': 'Fiyat',
    'cancel': 'İptal',
    'confirm': 'Onayla',
    
    // Reservation List
    'upcomingTab': 'Yaklaşan Rezervasyonlar',
    'pastTab': 'Geçmiş Rezervasyonlar',
    'openForSwap': 'Takas Aç',
    'cancelReservation': 'Rezervasyonu İptal Et',
    'confirmCancel': 'Emin misiniz? Ücret iadesi yapılmayacak',
    'no': 'Hayır',
    'yesCancel': 'Evet, İptal Et',
    
    // Swap
    'swapList': 'TAKAS LİSTESİ',
    'availableSwaps': 'Mevcut Takaslar',
    'mySwapOffers': 'Benim Takas Tekliflerim',
    'offeredBy': 'Teklif eden',
    'validity': 'Geçerlilik',
    'hoursLeft': '%.0f saat kaldı',
    'acceptSwap': 'Takası Kabul Et',
    'withdrawOffer': 'Teklifi Geri Al',
    
    // Profile
    'profile': 'Profil',
    'changePassword': 'Şifre Değiştir',
    'settings': 'Ayarlar',
    'language': 'Dil',
    'darkMode': 'Karanlık Mod',
    'notifications': 'Bildirimler',
    'logout': 'Çıkış Yap',
    'school': 'Okul',
    'cardId': 'Kart ID',
    'oldPassword': 'Eski Şifre',
    'newPassword': 'Yeni Şifre',
    'newPasswordConfirm': 'Yeni Şifre Tekrar',
    'save': 'Kaydet',
    
    // Admin
    'dashboard': 'Yönetici Paneli',
    'totalReservations': 'Toplam\nRezervasyon',
    'totalRevenue': 'Toplam\nGelir',
    'cancellationRate': 'İptal\nOranı',
    'wasteReport': 'İsraf\nRaporu',
    'addMeal': 'Yemek Ekle',
    'addMealDesc': 'Menüye yeni yemek ekle',
    'menuManagement': 'Menü Yönetimi',
    'menuManagementDesc': 'Mevcut yemekleri düzenle',
    'students': 'Öğrenciler',
    'studentsDesc': 'Öğrenci listesini görüntüle',
    'reports': 'Raporlar',
    'reportsDesc': 'Detaylı analitik ve raporlar',
    'schoolSettings': 'Okul Ayarları',
    'schoolSettingsDesc': 'Rezervasyon kuralları ve fiyatlandırma',
    
    // Status
    'reserved': 'REZERVE',
    'consumed': 'TÜKETİLDİ',
    'cancelled': 'İPTAL',
    'transferOpen': 'TAKAS AÇIK',
    'transferred': 'TRANSFER',
    
    // Messages
    'loginSuccess': 'Giriş başarılı',
    'loginError': 'E-posta veya şifre hatalı',
    'registerSuccess': 'Kayıt başarılı',
    'balanceLoadedSuccess': 'Bakiye başarıyla yüklendi',
    'reservationSuccess': 'Rezervasyon başarıyla oluşturuldu',
    'reservationCancelled': 'Rezervasyon iptal edildi',
    'swapOpened': 'Rezervasyon takasa açıldı',
    'swapAccepted': 'Takas başarıyla kabul edildi',
    'insufficientBalance': 'Yetersiz bakiye',
    'errorOccurred': 'Bir hata oluştu',
  };
  
  // English Strings
  static const Map<String, String> en = {
    // Auth
    'welcome': 'Welcome',
    'login': 'Login',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'forgotPassword': 'Forgot Password',
    'dontHaveAccount': "Don't have an account?",
    'alreadyHaveAccount': 'Already have an account?',
    'fullName': 'Full Name',
    'schoolEmail': 'School Email',
    'phone': 'Phone Number',
    'studentNumber': 'Student Number',
    
    // Home
    'welcomeBack': 'Welcome back,',
    'cardBalance': 'Card balance',
    'quickActions': 'Quick Actions',
    'createReservation': 'Create\nReservation',
    'swap': 'Swap',
    'qrPayment': 'QR Payment',
    'reservationList': 'Reservation\nList',
    'upcomingReservations': 'Upcoming Reservations',
    'adminPanel': 'Admin Panel',
    
    // Balance
    'loadBalance': 'Load Balance',
    'amountToLoad': 'Amount to Load',
    'minMax': 'Minimum: ₺%.0f - Maximum: ₺%.0f',
    'quickSelect': 'Quick Select',
    'transactionHistory': 'Transaction History',
    'balanceLoaded': 'Balance Load',
    'reservationPayment': 'Reservation Payment',
    'refund': 'Refund',
    'mockPaymentNote': '* This is a mock payment system. In production, you will be redirected to banking app.',
    
    // Reservations
    'filters': 'FILTERS',
    'selectDate': 'Select Date',
    'mealType': 'Meal Type',
    'mealPeriod': 'Meal Period',
    'normal': 'Normal',
    'vegetarian': 'Vegetarian',
    'vegan': 'Vegan',
    'glutenFree': 'Gluten Free',
    'breakfast': 'Breakfast',
    'lunch': 'Lunch',
    'dinner': 'Dinner',
    'spotsLeft': '%.0f spots left',
    'reservationPrice': 'Reservation Price',
    'walkInPrice': 'Walk-in',
    'reserve': 'Reserve',
    'confirmReservation': 'Confirm Reservation',
    'meal': 'Meal',
    'date': 'Date',
    'time': 'Time',
    'price': 'Price',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    
    // Reservation List
    'upcomingTab': 'Upcoming Reservations',
    'pastTab': 'Past Reservations',
    'openForSwap': 'Open for Swap',
    'cancelReservation': 'Cancel Reservation',
    'confirmCancel': 'Are you sure? No refund will be issued',
    'no': 'No',
    'yesCancel': 'Yes, Cancel',
    
    // Swap
    'swapList': 'SWAP LIST',
    'availableSwaps': 'Available Swaps',
    'mySwapOffers': 'My Swap Offers',
    'offeredBy': 'Offered by',
    'validity': 'Validity',
    'hoursLeft': '%.0f hours left',
    'acceptSwap': 'Accept Swap',
    'withdrawOffer': 'Withdraw Offer',
    
    // Profile
    'profile': 'Profile',
    'changePassword': 'Change Password',
    'settings': 'Settings',
    'language': 'Language',
    'darkMode': 'Dark Mode',
    'notifications': 'Notifications',
    'logout': 'Logout',
    'school': 'School',
    'cardId': 'Card ID',
    'oldPassword': 'Old Password',
    'newPassword': 'New Password',
    'newPasswordConfirm': 'Confirm New Password',
    'save': 'Save',
    
    // Admin
    'dashboard': 'Admin Dashboard',
    'totalReservations': 'Total\nReservations',
    'totalRevenue': 'Total\nRevenue',
    'cancellationRate': 'Cancellation\nRate',
    'wasteReport': 'Waste\nReport',
    'addMeal': 'Add Meal',
    'addMealDesc': 'Add new meal to menu',
    'menuManagement': 'Menu Management',
    'menuManagementDesc': 'Edit existing meals',
    'students': 'Students',
    'studentsDesc': 'View student list',
    'reports': 'Reports',
    'reportsDesc': 'Detailed analytics and reports',
    'schoolSettings': 'School Settings',
    'schoolSettingsDesc': 'Reservation rules and pricing',
    
    // Status
    'reserved': 'RESERVED',
    'consumed': 'CONSUMED',
    'cancelled': 'CANCELLED',
    'transferOpen': 'OPEN',
    'transferred': 'TRANSFERRED',
    
    // Messages
    'loginSuccess': 'Login successful',
    'loginError': 'Invalid email or password',
    'registerSuccess': 'Registration successful',
    'balanceLoadedSuccess': 'Balance loaded successfully',
    'reservationSuccess': 'Reservation created successfully',
    'reservationCancelled': 'Reservation cancelled',
    'swapOpened': 'Reservation opened for swap',
    'swapAccepted': 'Swap accepted successfully',
    'insufficientBalance': 'Insufficient balance',
    'errorOccurred': 'An error occurred',
  };
}

